// This file is auto-generated by file-based-routing plugin
// DO NOT EDIT MANUALLY - changes will be overwritten

import { lazy, Suspense } from 'react';
import type { RouteObject } from 'react-router-dom';


// Auto-generated imports
import Layout from './pages/layout';
import { loader as homeLoader } from './pages/page';
const HomePage = lazy(() => import('./pages/page'));
const AboutPage = lazy(() => import('./pages/(company)/about/page'));
const AboutMissionPage = lazy(() => import('./pages/(company)/about/(mission-vision-values)/mission'));
const AboutValuesPage = lazy(() => import('./pages/(company)/about/(mission-vision-values)/values'));
const AboutVisionPage = lazy(() => import('./pages/(company)/about/(mission-vision-values)/vision'));
const BlogSlugPage = lazy(() => import('./pages/blog/[[...slug]]/page'));
import DashboardLayout from './pages/dashboard/layout';
const DashboardPage = lazy(() => import('./pages/dashboard/page'));
import DashboardUsersLayout from './pages/dashboard/users/layout';
import { loader as dashboardUsersLoader } from './pages/dashboard/users/page';
const DashboardUsersPage = lazy(() => import('./pages/dashboard/users/page'));
import { loader as dashboardUsersIdLoader } from './pages/dashboard/users/[id]/page';
const DashboardUsersIdPage = lazy(() => import('./pages/dashboard/users/[id]/page'));
const DashboardUsersIdEditPage = lazy(() => import('./pages/dashboard/users/[id]/edit'));
const DocsSlugPage = lazy(() => import('./pages/docs/[...slug]/page'));
import { meta as routingDocsMeta } from './pages/routing-docs/page';
const RoutingDocsPage = lazy(() => import('./pages/routing-docs/page'));
const RoutingDocsCatchAllOptionalPage = lazy(() => import('./pages/routing-docs/catch-all-optional'));
const RoutingDocsCatchAllRequiredPage = lazy(() => import('./pages/routing-docs/catch-all-required'));
import { loader as serverActionsLoader } from './pages/server-actions/page';
const ServerActionsPage = lazy(() => import('./pages/server-actions/page'));
const React19DemoPage = lazy(() => import('./pages/(react-19-demo)/react-19-demo'));
const ClientExamplePage = lazy(() => import('./pages/client-example'));
const NavigationTestPage = lazy(() => import('./pages/navigation-test'));
import { loader as ssrExampleLoader } from './pages/ssr-example';
const SsrExamplePage = lazy(() => import('./pages/ssr-example'));

export const routes: RouteObject[] = [
  {
    path: "/",
    element: <Layout />,
    children: [
    {
      index: true,
      element: <Suspense fallback={<div>Loading...</div>}>
        <HomePage />
      </Suspense>,
      loader: homeLoader,
        },
    {
      path: "about",
      children: [
        {
          index: true,
          element: <Suspense fallback={<div>Loading...</div>}>
            <AboutPage />
          </Suspense>,
        },
        {
          path: "mission",
          element: <Suspense fallback={<div>Loading...</div>}>
            <AboutMissionPage />
          </Suspense>,
        },
        {
          path: "values",
          element: <Suspense fallback={<div>Loading...</div>}>
            <AboutValuesPage />
          </Suspense>,
        },
        {
          path: "vision",
          element: <Suspense fallback={<div>Loading...</div>}>
            <AboutVisionPage />
          </Suspense>,
        },
      ],
    },
    {
      path: "blog",
      children: [
        {
          path: "*",
          children: [
            {
              index: true,
              element: <Suspense fallback={<div>Loading...</div>}>
                <BlogSlugPage />
              </Suspense>,
            },
            {
              path: "*",
              element: <Suspense fallback={<div>Loading...</div>}>
                <BlogSlugPage />
              </Suspense>,
            },
          ],
        },
      ],
    },
    {
      path: "dashboard",
      element: <DashboardLayout />,
      children: [
        {
          index: true,
          element: <Suspense fallback={<div>Loading...</div>}>
            <DashboardPage />
          </Suspense>,
        },
        {
          path: "users",
          element: <DashboardUsersLayout />,
          children: [
            {
              index: true,
              element: <Suspense fallback={<div>Loading...</div>}>
                <DashboardUsersPage />
              </Suspense>,
              loader: dashboardUsersLoader,
            },
            {
              path: ":id",
              children: [
                {
                  index: true,
                  element: <Suspense fallback={<div>Loading...</div>}>
                    <DashboardUsersIdPage />
                  </Suspense>,
                  loader: dashboardUsersIdLoader,
                },
                {
                  path: "edit",
                  element: <Suspense fallback={<div>Loading...</div>}>
                    <DashboardUsersIdEditPage />
                  </Suspense>,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      path: "docs",
      children: [
        {
          path: "*",
          element: <Suspense fallback={<div>Loading...</div>}>
            <DocsSlugPage />
          </Suspense>,
        },
      ],
    },
    {
      path: "routing-docs",
      children: [
        {
          index: true,
          element: <Suspense fallback={<div>Loading...</div>}>
            <RoutingDocsPage />
          </Suspense>,
          handle: { meta: routingDocsMeta },
        },
        {
          path: "catch-all-optional",
          element: <Suspense fallback={<div>Loading...</div>}>
            <RoutingDocsCatchAllOptionalPage />
          </Suspense>,
        },
        {
          path: "catch-all-required",
          element: <Suspense fallback={<div>Loading...</div>}>
            <RoutingDocsCatchAllRequiredPage />
          </Suspense>,
        },
      ],
    },
    {
      path: "server-actions",
      element: <Suspense fallback={<div>Loading...</div>}>
        <ServerActionsPage />
      </Suspense>,
      loader: serverActionsLoader,
    },
    {
      path: "react-19-demo",
      element: <Suspense fallback={<div>Loading...</div>}>
        <React19DemoPage />
      </Suspense>,
    },
    {
      path: "client-example",
      element: <Suspense fallback={<div>Loading...</div>}>
        <ClientExamplePage />
      </Suspense>,
    },
    {
      path: "navigation-test",
      element: <Suspense fallback={<div>Loading...</div>}>
        <NavigationTestPage />
      </Suspense>,
    },
    {
      path: "ssr-example",
      element: <Suspense fallback={<div>Loading...</div>}>
        <SsrExamplePage />
      </Suspense>,
      loader: ssrExampleLoader,
    },
    ]
  }
];
