// This file is auto-generated by file-based-routing plugin
// DO NOT EDIT MANUALLY - changes will be overwritten

import type { RouteObject } from 'react-router-dom';


// Auto-generated imports
import Layout from './pages/layout';
import HomePage, { loader as homeLoader } from './pages/page';
import AboutPage from './pages/(company)/about/page';
import AboutMissionPage from './pages/(company)/about/(mission-vision-values)/mission';
import AboutValuesPage from './pages/(company)/about/(mission-vision-values)/values';
import AboutVisionPage from './pages/(company)/about/(mission-vision-values)/vision';
import DashboardLayout from './pages/dashboard/layout';
import DashboardPage from './pages/dashboard/page';
import DashboardUsersLayout from './pages/dashboard/users/layout';
import DashboardUsersPage, { loader as dashboardUsersLoader } from './pages/dashboard/users/page';
import DashboardUsersIdPage, { loader as dashboardUsersIdLoader } from './pages/dashboard/users/[id]/page';
import DashboardUsersIdEditPage from './pages/dashboard/users/[id]/edit';
import ServerActionsPage, { loader as serverActionsLoader } from './pages/server-actions/page';
import TestPage from './pages/test/index';
import UsersLayout from './pages/users/layout';
import UsersPage, { loader as usersLoader } from './pages/users/page';
import UsersIdPage, { loader as usersIdLoader } from './pages/users/[id]/page';
import UsersIdEditPage from './pages/users/[id]/edit';
import React19DemoPage from './pages/(react-19-demo)/react-19-demo';
import ClientExamplePage from './pages/client-example';
import NavigationTestPage from './pages/navigation-test';
import RoutingDocsPage from './pages/routing-docs';
import SsrExamplePage, { loader as ssrExampleLoader } from './pages/ssr-example';

export const routes: RouteObject[] = [
  {
    path: "/",
    element: <Layout />,
    children: [
    {
      index: true,
      element: <HomePage />,
      loader: homeLoader,
        },
    {
      path: "about",
      children: [
        {
          index: true,
          element: <AboutPage />,
        },
        {
          path: "mission",
          element: <AboutMissionPage />,
        },
        {
          path: "values",
          element: <AboutValuesPage />,
        },
        {
          path: "vision",
          element: <AboutVisionPage />,
        },
      ],
    },
    {
      path: "dashboard",
      element: <DashboardLayout />,
      children: [
        {
          index: true,
          element: <DashboardPage />,
        },
        {
          path: "users",
          element: <DashboardUsersLayout />,
          children: [
            {
              index: true,
              element: <DashboardUsersPage />,
              loader: dashboardUsersLoader,
            },
            {
              path: ":id",
              children: [
                {
                  index: true,
                  element: <DashboardUsersIdPage />,
                  loader: dashboardUsersIdLoader,
                },
                {
                  path: "edit",
                  element: <DashboardUsersIdEditPage />,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      path: "server-actions",
      element: <ServerActionsPage />,
      loader: serverActionsLoader,
    },
    {
      path: "test",
      element: <TestPage />,
    },
    {
      path: "users",
      element: <UsersLayout />,
      children: [
        {
          index: true,
          element: <UsersPage />,
          loader: usersLoader,
        },
        {
          path: ":id",
          children: [
            {
              index: true,
              element: <UsersIdPage />,
              loader: usersIdLoader,
            },
            {
              path: "edit",
              element: <UsersIdEditPage />,
            },
          ],
        },
      ],
    },
    {
      path: "react-19-demo",
      element: <React19DemoPage />,
    },
    {
      path: "client-example",
      element: <ClientExamplePage />,
    },
    {
      path: "navigation-test",
      element: <NavigationTestPage />,
    },
    {
      path: "routing-docs",
      element: <RoutingDocsPage />,
    },
    {
      path: "ssr-example",
      element: <SsrExamplePage />,
      loader: ssrExampleLoader,
    },
    ]
  }
];
