// This file is auto-generated by file-based-routing plugin
/** biome-ignore-all lint/suspicious/noExplicitAny: generated code */
/** biome-ignore-all assist/source/organizeImports: generated code  */
// DO NOT EDIT MANUALLY - changes will be overwritten

import { lazy, Suspense } from 'react';
import type { RouteObject } from 'react-router-dom';
import { createMeta } from '@consolidados/hono-vite-runtime/plugins/apply-meta';

// Auto-generated imports
import Layout from './pages/layout';
import { loader as homeLoader, meta as homeMeta } from './pages/page';
const HomePage = lazy(() => import('./pages/page'));
import LoadingPage from './pages/loading';
import NotFoundPage from './pages/not-found';
const AboutPage = lazy(() => import('./pages/(company)/about/page'));
const AboutMissionPage = lazy(() => import('./pages/(company)/about/(mission-vision-values)/mission'));
const AboutValuesPage = lazy(() => import('./pages/(company)/about/(mission-vision-values)/values'));
const AboutVisionPage = lazy(() => import('./pages/(company)/about/(mission-vision-values)/vision'));
const BlogSlugPage = lazy(() => import('./pages/blog/[[...slug]]/page'));
import DashboardLayout from './pages/dashboard/layout';
const DashboardPage = lazy(() => import('./pages/dashboard/page'));
import DashboardUsersLayout from './pages/dashboard/users/layout';
import { loader as dashboardUsersLoader } from './pages/dashboard/users/page';
const DashboardUsersPage = lazy(() => import('./pages/dashboard/users/page'));
import DashboardUsersLoadingPage from './pages/dashboard/users/loading';
import { loader as dashboardUsersIdLoader, meta as dashboardUsersIdMeta } from './pages/dashboard/users/[id]/page';
const DashboardUsersIdPage = lazy(() => import('./pages/dashboard/users/[id]/page'));
import { loader as dashboardUsersIdEditLoader, meta as dashboardUsersIdEditMeta } from './pages/dashboard/users/[id]/edit';
const DashboardUsersIdEditPage = lazy(() => import('./pages/dashboard/users/[id]/edit'));
const DocsSlugPage = lazy(() => import('./pages/docs/[...slug]/page'));
import { meta as routingDocsMeta } from './pages/routing-docs/page';
const RoutingDocsPage = lazy(() => import('./pages/routing-docs/page'));
const RoutingDocsCatchAllOptionalPage = lazy(() => import('./pages/routing-docs/catch-all-optional'));
const RoutingDocsCatchAllRequiredPage = lazy(() => import('./pages/routing-docs/catch-all-required'));
import { loader as serverActionsLoader } from './pages/server-actions/page';
const ServerActionsPage = lazy(() => import('./pages/server-actions/page'));
const React19DemoPage = lazy(() => import('./pages/(react-19-demo)/react-19-demo'));
const ClientExamplePage = lazy(() => import('./pages/client-example'));
const NavigationTestPage = lazy(() => import('./pages/navigation-test'));
import { loader as ssrExampleLoader } from './pages/ssr-example';
const SsrExamplePage = lazy(() => import('./pages/ssr-example'));

export const routes: RouteObject[] = [
  {
    path: "/",
    element: <Suspense><Layout /></Suspense>,
    errorElement: <NotFoundPage/>,
    children: [
      {
        index: true,
        element: <Suspense fallback={<LoadingPage />}>
          <HomePage />
        </Suspense>,
        loader: homeLoader,
        handle: { meta: ({ data, params }: any) => createMeta(homeMeta, { data, params }) },
      },
      {
        path: "about",
        children: [
          {
            index: true,
            element: <Suspense>
              <AboutPage />
            </Suspense>,
          },
          {
            path: "mission",
            element: <Suspense>
              <AboutMissionPage />
            </Suspense>,
          },
          {
            path: "values",
            element: <Suspense>
              <AboutValuesPage />
            </Suspense>,
          },
          {
            path: "vision",
            element: <Suspense>
              <AboutVisionPage />
            </Suspense>,
          },
        ],
      },
      {
        path: "blog",
        children: [
          {
            index: true,
            element: <Suspense>
              <BlogSlugPage />
            </Suspense>,
          },
          {
            path: "*",
            element: <Suspense>
              <BlogSlugPage />
            </Suspense>,
          },
        ],
      },
      {
        path: "dashboard",
        element: <DashboardLayout />,
        children: [
          {
            index: true,
            element: <Suspense>
              <DashboardPage />
            </Suspense>,
          },
          {
            path: "users",
            element: <DashboardUsersLayout />,
            children: [
              {
                index: true,
                element: <Suspense fallback={<DashboardUsersLoadingPage />}>
                  <DashboardUsersPage />
                </Suspense>,
                loader: dashboardUsersLoader,
              },
              {
                path: ":id",
                children: [
                  {
                    index: true,
                    element: <Suspense>
                      <DashboardUsersIdPage />
                    </Suspense>,
                    loader: dashboardUsersIdLoader,
                handle: { meta: ({ data, params }: any) => createMeta(dashboardUsersIdMeta, { data, params }) },
                  },
                  {
                    path: "edit",
                    element: <Suspense>
                      <DashboardUsersIdEditPage />
                    </Suspense>,
                    loader: dashboardUsersIdEditLoader,
                    handle: { meta: ({ data, params }: any) => createMeta(dashboardUsersIdEditMeta, { data, params }) },
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        path: "docs",
        children: [
          {
            path: "*",
            element: <Suspense>
              <DocsSlugPage />
            </Suspense>,
          },
        ],
      },
      {
        path: "routing-docs",
        children: [
          {
            index: true,
            element: <Suspense>
              <RoutingDocsPage />
            </Suspense>,
        handle: { meta: ({ data, params }: any) => createMeta(routingDocsMeta, { data, params }) },
          },
          {
            path: "catch-all-optional",
            element: <Suspense>
              <RoutingDocsCatchAllOptionalPage />
            </Suspense>,
          },
          {
            path: "catch-all-required",
            element: <Suspense>
              <RoutingDocsCatchAllRequiredPage />
            </Suspense>,
          },
        ],
      },
      {
        path: "server-actions",
        element: <Suspense>
          <ServerActionsPage />
        </Suspense>,
        loader: serverActionsLoader,
      },
      {
        path: "react-19-demo",
        element: <Suspense>
          <React19DemoPage />
        </Suspense>,
      },
      {
        path: "client-example",
        element: <Suspense>
          <ClientExamplePage />
        </Suspense>,
      },
      {
        path: "navigation-test",
        element: <Suspense>
          <NavigationTestPage />
        </Suspense>,
      },
      {
        path: "ssr-example",
        element: <Suspense>
          <SsrExamplePage />
        </Suspense>,
        loader: ssrExampleLoader,
      },
    ]
  }
];
