/**
 * File-Based Routing Plugin - Type Generator Module
 * Generates TypeScript types for type-safe routing
 */

import type { RouteNode } from "./types";

export interface GeneratedTypes {
	/** Path to generated types file */
	filePath: string;
	/** Generated TypeScript content */
	content: string;
}

/**
 * Extract all route paths and their params from route tree
 */
function extractRoutePaths(node: RouteNode, parentPath = ""): RouteInfo[] {
	const routes: RouteInfo[] = [];

	// Skip root node path
	const currentPath =
		node.path === "/" ? parentPath : `${parentPath}/${node.path}`;

	// Collect params from dynamic segments
	const params: string[] = [];
	if (node.isDynamic && node.path.startsWith(":")) {
		// Extract param name (":id" -> "id")
		params.push(node.path.slice(1));
	}

	// If this node has a page, it's a valid route
	if (node.page) {
		// Get loader data type if available
		const loaderType = node.page.hasLoader
			? `${node.page.componentName}LoaderData`
			: "undefined";

		routes.push({
			path: currentPath || "/",
			params,
			loaderType,
			hasLoader: node.page.hasLoader,
		});
	}

	// Recurse through children, accumulating params
	for (const child of node.children) {
		const childRoutes = extractRoutePaths(child, currentPath);

		// Inherit parent params
		for (const route of childRoutes) {
			route.params = [...params, ...route.params];
		}

		routes.push(...childRoutes);
	}

	return routes;
}

interface RouteInfo {
	path: string;
	params: string[];
	loaderType: string;
	hasLoader: boolean;
}

/**
 * Generate TypeScript interface for route params
 */
function generateParamsType(params: string[]): string {
	if (params.length === 0) {
		return "{}";
	}

	const fields = params.map((param) => `${param}: string`).join("; ");
	return `{ ${fields} }`;
}

/**
 * Generate route info type for each route
 */
function generateRouteInfoType(route: RouteInfo): string {
	const paramsType = generateParamsType(route.params);
	return `  '${route.path}': { params: ${paramsType}; loader: ${route.loaderType} };`;
}

/**
 * Generate TypeScript declaration file content
 */
export function generateTypeDeclarations(routeTree: RouteNode): string {
	// Extract all routes
	const routes = extractRoutePaths(routeTree);

	// Filter out duplicate paths (can happen with index routes)
	const uniqueRoutes = routes.reduce(
		(acc, route) => {
			if (!acc.has(route.path)) {
				acc.set(route.path, route);
			}
			return acc;
		},
		new Map<string, RouteInfo>(),
	);

	// Generate route info types
	const routeInfoTypes = Array.from(uniqueRoutes.values())
		.map(generateRouteInfoType)
		.join("\n");

	// Generate path union type
	const paths = Array.from(uniqueRoutes.keys())
		.map((path) => `  | '${path}'`)
		.join("\n");

	// Build complete type declaration
	const content = `/**
 * Auto-generated by file-based-routing plugin
 * DO NOT EDIT MANUALLY - changes will be overwritten
 */

/**
 * Map of all routes with their params and loader data
 */
export interface AppRoutes {
${routeInfoTypes}
}

/**
 * Union type of all valid route paths
 * Use for type-safe navigation
 */
export type AppRoutePaths =
${paths};

/**
 * Extract params type for a specific route
 */
export type RouteParams<T extends AppRoutePaths> = AppRoutes[T]['params'];

/**
 * Extract loader data type for a specific route
 */
export type LoaderData<T extends AppRoutePaths> = AppRoutes[T]['loader'];

/**
 * Type-safe navigation helper types
 *
 * Example usage:
 *
 * import type { AppRoutePaths, RouteParams } from './.react-router/types/routes';
 *
 * function navigateTo(path: AppRoutePaths, params?: RouteParams<typeof path>) {
 *   // Type-safe navigation logic
 * }
 */
export type NavigateOptions<T extends AppRoutePaths> = {
  to: T;
  params: RouteParams<T>;
};
`;

	return content;
}

/**
 * Generate loader data type declarations
 *
 * Note: This generates stub types. Actual loader return types
 * should be manually declared by users in their route files.
 */
export function generateLoaderTypeStubs(routeTree: RouteNode): string {
	const routes = extractRoutePaths(routeTree);

	// Find routes with loaders
	const loadersWithTypes = routes
		.filter((route) => route.hasLoader)
		.map((route) => route.loaderType)
		.filter((type, index, self) => self.indexOf(type) === index); // unique

	if (loadersWithTypes.length === 0) {
		return "";
	}

	const stubs = loadersWithTypes
		.map(
			(loaderType) => `/**
 * Loader data type for ${loaderType.replace("LoaderData", "")}
 *
 * TODO: Define the actual return type in your route file:
 *
 * export interface ${loaderType} {
 *   // Your loader data structure
 * }
 */
export interface ${loaderType} {
  [key: string]: unknown;
}`,
		)
		.join("\n\n");

	return `\n\n// Loader Data Type Stubs\n// Override these in your route files\n\n${stubs}`;
}
